### PR TITLE
Add local install options and automatic conversion

### PR DESCRIPTION
**Pull request by noklam**
- [x]  Adding setup.py allow installing the package locally, first step before having  a proper pip package. `python setup.py` or `pip install -e .` will do it.
- [x] For now report_on_dataframe only prints the possible conversion. It should return a dictionary/dataframe, which can be consumed later to automatically convert the dtype. As optimization depends on the use case, may provide two options as first step. 
1. Optimize computation (use fp32 if possible)
2. Optimize memory (use fp16 whenever possible)
3. Better handling cateogry dtype (handle NaN)

### CODE REVIEW

**Comment by noklam** [comment]
It's not fully done yet, but here is a working example for demonstrating how to use it. Some tricky part when casting int64 -> Int8 (the new pandas dtype which includes NA) need to pass a `errors='ignore` flag.

any thought?
https://noklam.github.io/blog/python/pandas/optimization/2020/11/10/Pandas-memory-optimization.html
(Edited to new site)

**Comment by neomatrix369** [comment]
@noklam this is good work, I was going to suggest to @ianozsvald that he also give suggestions on `float` types but your PR might be even covering that

**Comment by noklam** [comment]
Added some bug fix, black formatted and fallback to numpy dtypes (int16, int32, int64).

I can reproduce Ian's original result -> the sell_prices.csv shrink to 85Mb, however, on my dataset it only shrink 10% now. I need to have further checking why is that.

Edited: Looks like it is due to when converting object -> category, NaN is causing issue as we cannot use `==` to compare them, will fix it tomorrow.

**Comment by noklam** [comment]
In pandas >=1.1.0, a compare method seems to deal with comparing two series/df much easier, have better handling with category dtype with NaN now! @ianozsvald

**Comment by noklam** [comment]
any comments?

**Comment by ianozsvald** [comment]
Apologies both, I'm useless at the moment. I've got a 4 month old infant and all my spare time goes to him. As such - would either of your @noklam or @neomatrix369 like to take ownership of this project? All I'd ask in a fork is a note that I wrote the first version, after that you could do as you wished and I won't be a blocker :-)
As for the tool's development - I needed this for talks and a client problem earlier in the year but that's less pressing now, so this isn't my focus. I will note that Matt Wrocklin of Dask said he'd promote a tool such as this as it is a driver of issues into Dask, so there's definitely a need out there for a tool like this. 
Thoughts?

**Comment by noklam** [comment]
@ianozsvald Hey, Congrats on your newborn, tough time! Hope you are doing fine. I am happy to fork it as I always find myself writing manual code to trim down datasets.

**Comment by noklam** [comment]
I create the fork and a doc site for now, I am still exploring how to play with the nbdev system. Once it is ready I may push a package to PyPI, might do it this week or next week. Let me know if you want me to supplement anything.


fork repo: https://github.com/noklam/dtype_diet
doc: https://noklam.github.io/dtype_diet/

**Comment by neomatrix369** [comment]
> Apologies both, I'm useless at the moment. I've got a 4 month old infant and all my spare time goes to him. As such - would either of your @noklam or @neomatrix369 like to take ownership of this project? All I'd ask in a fork is a note that I wrote the first version, after that you could do as you wished and I won't be a blocker :-)
> As for the tool's development - I needed this for talks and a client problem earlier in the year but that's less pressing now, so this isn't my focus. I will note that Matt Wrocklin of Dask said he'd promote a tool such as this as it is a driver of issues into Dask, so there's definitely a need out there for a tool like this.
> Thoughts?

Congrats again Ian. Happy to discuss this and take this further, although you have done most of the groundwork, I think our inputs would be icing on the cake I think. At least the feature I'd like to add is discussable but I can always create a PR and take it from there. 

@noklam let's chat about this change and we can progress it together as @ianozsvald is going to be busy-bee for some time!

**Comment by noklam** [comment]
@neomatrix369 Sure, if it is fine for you, feel free to open an issue for discussion in the fork repo.

**Comment by noklam** [comment]
I create the version 0.0.1 on pypi now.
https://pypi.org/project/dtype-diet/

docs: https://noklam.github.io/dtype_diet/

**Comment by noklam** [comment]
I actually never notice the `issues` page is disabled by default. Until today I try to clean up my PyPi package and I notice there are actually people downloading this😅

**Pull request closed without merging**
